name: Fetch Package Versions

on:
  workflow_dispatch:

jobs:
  fetch-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @octokit/rest rxjs @octokit/plugin-rest-endpoint-methods

      - name: Run script
        run: |
          node -e "
            const { Octokit } = require('@octokit/rest');
            const { from, throwError } = require('rxjs');
            const { catchError, map } = require('rxjs/operators');

            const octokit = new Octokit();

            const owner = 'YOUR_GITHUB_USERNAME';
            const packageName = 'decluttarr';
            const packageType = 'container';
            const numVersions = 10; // Number of versions to fetch
            const page = 1; // Page number
            const token = process.env.GITHUB_TOKEN;

            const packageVersions$ = from(
              octokit.rest.packages.getAllPackageVersionsForPackageOwnedByUser({
                package_type: packageType,
                package_name: packageName,
                username: owner,
                per_page: numVersions,
                page
              })
            ).pipe(
              catchError(err => throwError('Failed to fetch package versions: ' + err.message)),
              map(response => response.data)
            );

            packageVersions$.subscribe(
              resp => console.log('Response:', resp),
              error => console.error('Error:', error)
            );
          "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
