name: Check Package Versions

on:
  workflow_dispatch:
    inputs:
      package-name:
        description: 'Package Name'
        required: true
        default: 'decluttarr'
      package-type:
        description: 'Package Type'
        required: true
        default: 'container'

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @octokit/rest rxjs @octokit/plugin-rest-endpoint-methods typescript

      - name: Compile TypeScript
        run: npx tsc .github/workflows/get-versions.ts

      - name: Run script
        run: node .github/workflows/get-versions.js ${{ secrets.GITHUB_TOKEN }} ${{ github.event.inputs.package-name }} ${{ github.event.inputs.package-type }}
        env:
          GITHUB_API_URL: 'https://api.github.com'
          PACKAGE_NAME: ${{ github.event.inputs.package-name }}
          PACKAGE_TYPE: ${{ github.event.inputs.package-type }}
